name: Secrets and Environment Variables

on: workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env:
      MY_APP_ID: ${{ vars.API_KEY }}

    steps:
      - name: Read a variable
        run: echo "My APP_ID value is ${{ vars.API_KEY }}"

      - name: Tell me a secret!
        run: echo "My existing secret is ${{ secrets.API_KEY }}"

      - name: Unset secret
        run: echo "My unknown secret is ${{ secrets.DOES_NOT_EXIST }}"

      - name: Github stuff
        run: echo "My Github repo is called ${{ github.repository }}"

      - name: Read an env variable
        run: echo "My APP_ID value is ${{ env.API_KEY }} (also accessible as $MY_APP_ID)"

      - uses: actions/checkout@v2
      - name: Read the env from an external script
        run: |
          chmod +x .github/scripts/custom.sh
          .github/scripts/custom.sh
        shell: bash

  top-secret-production:
    runs-on: ubuntu-latest
    environment: production
    env:
      APP_ID: ${{ vars.API_KEY }}

    steps:
      - name: Read a variable
        run: echo "My APP_ID value in the production job is $APP_ID"
